#!/bin/bash
set -eu
cd "$(dirname "$0")/.."

function main () {
    outdir=download

    IFS=' ' read name digest url
    if test -z "$name"; then exit 1; fi
    cachefile="${name%.*}-${digest}.${name##*.}"
    if test -e "$outdir/$name" && test -f "$outdir/.sha256sum/$cachefile" && echo "$digest  $outdir/$name" | shasum -a 256 --status -c -; then exit 0; fi
    if ! test -f "$outdir/.sha256sum/$cachefile" || ! echo "$digest  $outdir/.sha256sum/$cachefile" | shasum -a 256 --status -c -; then
        mkdir -p $outdir/.sha256sum
        curl -LsSf "$url" -o "$outdir/.sha256sum/$cachefile.tmp"
        echo "$digest  $outdir/.sha256sum/$cachefile.tmp" | shasum -a 256 --status -c -
        mv "$outdir/.sha256sum/$cachefile.tmp" "$outdir/.sha256sum/$cachefile"
    fi
    rm -f "$outdir/$name"
    cp "$outdir/.sha256sum/$cachefile" "$outdir/$name"
}

grep -v -E '^#|^\s*$' download.txt | sort -k 1b,1 | join -j 1 - <(printf "%s\n" "$@") | main
